//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesDepartmentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.Schedule = new HashSet<Schedule>();
            this.Vacation_Schedule = new HashSet<Vacation_Schedule>();
        }
    
        public long Id_Profile { get; set; }
        public string Full_Name { get; set; }
        public System.DateTime Date_of_Birth { get; set; }
        public string Place_of_Birth { get; set; }
        public string Place_of_Registration { get; set; }
        public string Criminal_Record_Information { get; set; }
        public string Phone_Number { get; set; }
        public string Mail_Address { get; set; }
        public string Passport_Data { get; set; }
        public string SNILS { get; set; }
        public long Id_Position { get; set; }
    
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Schedule> Schedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacation_Schedule> Vacation_Schedule { get; set; }
    }
}
