//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesDepartmentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long Id_Schedule { get; set; }
        public long Id_Profile { get; set; }
        public long Id_DayOfTheWeek { get; set; }
        public string Status { get; set; }
        public string Duration { get; set; }
        public Nullable<int> Cabinet { get; set; }
    
        public virtual DayOfTheWeek DayOfTheWeek { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
