//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesDepartmentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staffing
    {
        public long Id_Staffing { get; set; }
        public long Id_Position { get; set; }
        public double Number_Of_Staff_Units { get; set; }
        public decimal Salary { get; set; }
        public decimal Night_Shift_Allowance { get; set; }
        public decimal Premium { get; set; }
        public double District_Coefficient { get; set; }
        public decimal In_All { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
