//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumanResourcesDepartmentApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation_Schedule
    {
        public long Id_Vacation_Schedule { get; set; }
        public long Id_Profile { get; set; }
        public System.DateTime Start_Date { get; set; }
        public int Duration { get; set; }
        public System.DateTime End_Date { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
